export const INTERNAL_SERVER_ERROR = "Internal Server Error";
export const NOT_FOUND_ERROR = "Resource Not Found";
export const UNAUTHORIZED_ERROR = "Unauthorized";
export const FORBIDDEN_ERROR = "Forbidden Access";
export const BAD_REQUEST_ERROR = "Bad Request";
export const CONNECTION_ESTABLISHED = "Connection established by";
export const CONNECTION_ERROR = "Error while connecting";
export const LOGIN_SUCCESS = "Logged in successfully";
export const LOGOUT_SUCCESS = "Logged out successfully";
export const INVALID_CREDENTIALS = "Invalid email or password";
export const CREATE_SUCCESS = (item: string) => `${item} created successfully`;
export const UPDATE_SUCCESS = (item: string) => `${item} updated successfully`;
export const DELETE_SUCCESS = (item: string) => `${item} deleted successfully`;
export const GET_SUCCESS = (item: string) => `${item} retrieved successfully`;
