name: Deploy to EC2

on:
  push:
    branches:
      - master  # Jab bhi master branch pe push hoga, action chalega

jobs:
  deploy:
    runs-on: self-hosted  # Tumhara EC2 runner isko execute karega

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Tumhare project ka Node.js version

      - name: Create .env File
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" > .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Install Dependencies & Build
        run: |
          npm install
          npm run build

      - name: Restart Server with PM2
        run: |
          pm2 restart all || pm2 start dist/server.js --name "uttam-kheti-api"
          pm2 save
