name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Compile TypeScript
        run: npm run build

      - name: Start Server with PM2
        run: |
          npm install -g pm2
          pm2 stop all || true
          pm2 start dist/server.js --name uttam-kheti-api
